@startuml
set namespaceSeparator ::

class "pawfection::homepage.dart::Homepage" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "pawfection::homepage.dart::Homepage"

class "pawfection::repository::storage_repository.dart::StorageRepository" {
  -FirebaseStorage _storage
  +dynamic uploadImageToStorage()
}

"pawfection::repository::storage_repository.dart::StorageRepository" o-- "firebase_storage::firebase_storage.dart::FirebaseStorage"

class "pawfection::repository::task_repository.dart::TaskRepository" {
  +CollectionReference<Object?> taskcollection
  +TaskService taskService
  +Stream<QuerySnapshot<Object?>> tasks
  +dynamic addTask()
  +void updateTask()
  +void deleteTask()
  +dynamic findTaskByTaskID()
  +dynamic getTaskList()
}

"pawfection::repository::task_repository.dart::TaskRepository" o-- "cloud_firestore::cloud_firestore.dart::CollectionReference<Object>"
"pawfection::repository::task_repository.dart::TaskRepository" o-- "pawfection::service::task_service.dart::TaskService"
"pawfection::repository::task_repository.dart::TaskRepository" o-- "dart::async::Stream<QuerySnapshot<Object>>"

class "pawfection::repository::user_repository.dart::UserRepository" {
  +CollectionReference<Object?> usercollection
  +UserService userService
  +Stream<QuerySnapshot<Object?>> users
  +dynamic findUserByUUID()
  +void addUser()
  +void updateUser()
  +void deleteUser()
  +dynamic getUserList()
  +dynamic currentUser()
}

"pawfection::repository::user_repository.dart::UserRepository" o-- "cloud_firestore::cloud_firestore.dart::CollectionReference<Object>"
"pawfection::repository::user_repository.dart::UserRepository" o-- "pawfection::service::user_service.dart::UserService"
"pawfection::repository::user_repository.dart::UserRepository" o-- "dart::async::Stream<QuerySnapshot<Object>>"

class "pawfection::repository::pet_repository.dart::PetRepository" {
  +CollectionReference<Object?> petcollection
  +PetService petService
  +Stream<QuerySnapshot<Object?>> pets
  +dynamic addPet()
  +void updatePet()
  +void deletePet()
  +dynamic findUserByPetID()
  +dynamic findPetByPetID()
  +dynamic getPetList()
}

"pawfection::repository::pet_repository.dart::PetRepository" o-- "cloud_firestore::cloud_firestore.dart::CollectionReference<Object>"
"pawfection::repository::pet_repository.dart::PetRepository" o-- "pawfection::service::pet_service.dart::PetService"
"pawfection::repository::pet_repository.dart::PetRepository" o-- "dart::async::Stream<QuerySnapshot<Object>>"

class "pawfection::loginView.dart::LoginView" {
  -FirebaseAuth _auth
  +UserRepository userRepository
  +Duration loginTime
  -dynamic _authUser()
  -dynamic _signupUser()
  -dynamic _recoverPassword()
  +Widget build()
}

"pawfection::loginView.dart::LoginView" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"pawfection::loginView.dart::LoginView" o-- "pawfection::repository::user_repository.dart::UserRepository"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "pawfection::loginView.dart::LoginView"

class "pawfection::firebase_options.dart::DefaultFirebaseOptions" {
  {static} +FirebaseOptions web
  {static} +FirebaseOptions android
  {static} +FirebaseOptions ios
  {static} +FirebaseOptions macos
  {static} +FirebaseOptions currentPlatform
}

"pawfection::firebase_options.dart::DefaultFirebaseOptions" o-- "firebase_core_platform_interface::firebase_core_platform_interface.dart::FirebaseOptions"

class "pawfection::managerscreens::m_create_task_screen.dart::MCreateTaskScreen" {
  +String imagePath
  +State<MCreateTaskScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pawfection::managerscreens::m_create_task_screen.dart::MCreateTaskScreen"

class "pawfection::managerscreens::m_create_task_screen.dart::_MCreateTaskScreenState" {
  -GlobalKey<FormState> _profileKey
  +GlobalKey<FormState> formKey
  +TaskRepository taskRepository
  +PetRepository petRepository
  +UserRepository userRepository
  -dynamic _form
  +dynamic alertmessage
  -FirebaseAuth _auth
  -void _showDialog()
  +Widget build()
  +Widget buildPetList()
  +Widget buildVolunteerList()
  -List<Widget> _buildForm()
  -List<Widget> _buildCupertinoForm()
}

"pawfection::managerscreens::m_create_task_screen.dart::_MCreateTaskScreenState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"pawfection::managerscreens::m_create_task_screen.dart::_MCreateTaskScreenState" o-- "pawfection::repository::task_repository.dart::TaskRepository"
"pawfection::managerscreens::m_create_task_screen.dart::_MCreateTaskScreenState" o-- "pawfection::repository::pet_repository.dart::PetRepository"
"pawfection::managerscreens::m_create_task_screen.dart::_MCreateTaskScreenState" o-- "pawfection::repository::user_repository.dart::UserRepository"
"pawfection::managerscreens::m_create_task_screen.dart::_MCreateTaskScreenState" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"flutter::src::widgets::framework.dart::State" <|-- "pawfection::managerscreens::m_create_task_screen.dart::_MCreateTaskScreenState"

class "pawfection::managerscreens::m_volunteerlist_screen.dart::MVolunteerListScreen" {
  +State<MVolunteerListScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pawfection::managerscreens::m_volunteerlist_screen.dart::MVolunteerListScreen"

class "pawfection::managerscreens::m_volunteerlist_screen.dart::_MVolunteerListScreenState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "pawfection::managerscreens::m_volunteerlist_screen.dart::_MVolunteerListScreenState"

class "pawfection::managerscreens::m_volunteerlist_screen.dart::UserItem" {
  +User user
  +Widget build()
}

"pawfection::managerscreens::m_volunteerlist_screen.dart::UserItem" o-- "pawfection::models::user.dart::User"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "pawfection::managerscreens::m_volunteerlist_screen.dart::UserItem"

class "pawfection::managerscreens::m_volunteerlist_screen.dart::EmptyView" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "pawfection::managerscreens::m_volunteerlist_screen.dart::EmptyView"

class "pawfection::managerscreens::m_update_task_screen.dart::MUpdateTaskScreen" {
  +Task task
  +State<MUpdateTaskScreen> createState()
}

"pawfection::managerscreens::m_update_task_screen.dart::MUpdateTaskScreen" o-- "pawfection::models::task.dart::Task"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pawfection::managerscreens::m_update_task_screen.dart::MUpdateTaskScreen"

class "pawfection::managerscreens::m_update_task_screen.dart::_MUpdateTaskScreenState" {
  -GlobalKey<FormState> _profileKey
  +GlobalKey<FormState> formKey
  +TaskRepository taskRepository
  -dynamic _form
  +dynamic alertmessage
  -void _showDialog()
  +Widget build()
  -List<Widget> _buildForm()
  -List<Widget> _buildCupertinoForm()
}

"pawfection::managerscreens::m_update_task_screen.dart::_MUpdateTaskScreenState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"pawfection::managerscreens::m_update_task_screen.dart::_MUpdateTaskScreenState" o-- "pawfection::repository::task_repository.dart::TaskRepository"
"flutter::src::widgets::framework.dart::State" <|-- "pawfection::managerscreens::m_update_task_screen.dart::_MUpdateTaskScreenState"

class "pawfection::managerscreens::m_dashboard_screen.dart::MDashboardScreen" {
  +State<MDashboardScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pawfection::managerscreens::m_dashboard_screen.dart::MDashboardScreen"

class "pawfection::managerscreens::m_dashboard_screen.dart::_MDashboardScreenState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "pawfection::managerscreens::m_dashboard_screen.dart::_MDashboardScreenState"

class "pawfection::managerscreens::m_dashboard_screen.dart::TaskItem" {
  +Task task
  +Widget build()
}

"pawfection::managerscreens::m_dashboard_screen.dart::TaskItem" o-- "pawfection::models::task.dart::Task"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "pawfection::managerscreens::m_dashboard_screen.dart::TaskItem"

class "pawfection::managerscreens::m_dashboard_screen.dart::EmptyView" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "pawfection::managerscreens::m_dashboard_screen.dart::EmptyView"

class "pawfection::managerscreens::m_pet_screen.dart::MPetScreen" {
  +State<MPetScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pawfection::managerscreens::m_pet_screen.dart::MPetScreen"

class "pawfection::managerscreens::m_pet_screen.dart::_MPetScreenState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "pawfection::managerscreens::m_pet_screen.dart::_MPetScreenState"

class "pawfection::managerscreens::m_pet_screen.dart::PetItem" {
  +Pet pet
  +Widget build()
}

"pawfection::managerscreens::m_pet_screen.dart::PetItem" o-- "pawfection::models::pet.dart::Pet"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "pawfection::managerscreens::m_pet_screen.dart::PetItem"

class "pawfection::managerscreens::m_pet_screen.dart::EmptyView" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "pawfection::managerscreens::m_pet_screen.dart::EmptyView"

class "pawfection::managerscreens::m_create_pet_screen.dart::MCreatePetScreen" {
  +String imageURL
  +State<MCreatePetScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pawfection::managerscreens::m_create_pet_screen.dart::MCreatePetScreen"

class "pawfection::managerscreens::m_create_pet_screen.dart::_MCreatePetScreenState" {
  -GlobalKey<FormState> _profileKey
  +GlobalKey<FormState> formKey
  +PetRepository petRepository
  -dynamic _form
  +dynamic alertmessage
  +Widget build()
  -List<Widget> _buildForm()
  -List<Widget> _buildCupertinoForm()
}

"pawfection::managerscreens::m_create_pet_screen.dart::_MCreatePetScreenState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"pawfection::managerscreens::m_create_pet_screen.dart::_MCreatePetScreenState" o-- "pawfection::repository::pet_repository.dart::PetRepository"
"flutter::src::widgets::framework.dart::State" <|-- "pawfection::managerscreens::m_create_pet_screen.dart::_MCreatePetScreenState"

class "pawfection::managerscreens::m_update_pet_screen.dart::MUpdatePetScreen" {
  +String imageURL
  +Pet pet
  +State<MUpdatePetScreen> createState()
}

"pawfection::managerscreens::m_update_pet_screen.dart::MUpdatePetScreen" o-- "pawfection::models::pet.dart::Pet"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pawfection::managerscreens::m_update_pet_screen.dart::MUpdatePetScreen"

class "pawfection::managerscreens::m_update_pet_screen.dart::_MUpdatePetScreenState" {
  -GlobalKey<FormState> _profileKey
  +GlobalKey<FormState> formKey
  +PetRepository petRepository
  -dynamic _form
  +dynamic alertmessage
  +void initState()
  +Widget build()
  -List<Widget> _buildForm()
  -List<Widget> _buildCupertinoForm()
}

"pawfection::managerscreens::m_update_pet_screen.dart::_MUpdatePetScreenState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"pawfection::managerscreens::m_update_pet_screen.dart::_MUpdatePetScreenState" o-- "pawfection::repository::pet_repository.dart::PetRepository"
"flutter::src::widgets::framework.dart::State" <|-- "pawfection::managerscreens::m_update_pet_screen.dart::_MUpdatePetScreenState"

class "pawfection::managerscreens::m_create_user_screen.dart::MCreateUserScreen" {
  +String imagePath
  +State<MCreateUserScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pawfection::managerscreens::m_create_user_screen.dart::MCreateUserScreen"

class "pawfection::managerscreens::m_create_user_screen.dart::_MCreateUserScreenState" {
  -GlobalKey<FormState> _profileKey
  +GlobalKey<FormState> formKey
  +UserRepository userRepository
  -dynamic _form
  +dynamic alertmessage
  -List<dynamic> _experiences
  +List<dynamic> preferences
  -int _selectedFruit
  -void _showDialog()
  +Widget build()
  -List<Widget> _buildForm()
  -List<Widget> _buildCupertinoForm()
}

"pawfection::managerscreens::m_create_user_screen.dart::_MCreateUserScreenState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"pawfection::managerscreens::m_create_user_screen.dart::_MCreateUserScreenState" o-- "pawfection::repository::user_repository.dart::UserRepository"
"flutter::src::widgets::framework.dart::State" <|-- "pawfection::managerscreens::m_create_user_screen.dart::_MCreateUserScreenState"

class "pawfection::models::user.dart::User" {
  +String referenceId
  +String username
  +String email
  +String role
  +List<Timestamp?> availabledates
  +List<String?> preferences
  +List<String?> experiences
  +String profilepicture
  +String contactnumber
  +String bio
  +String toString()
}

class "pawfection::models::pet.dart::Pet" {
  +String? referenceId
  +String name
  +String? breed
  +String? description
  +String? thingstonote
  +String profilepicture
  +String toString()
}

class "pawfection::models::task.dart::Task" {
  +String? referenceId
  +String name
  +String createdby
  +String assignedto
  +String description
  +String status
  +List<String?> resources
  +String contactperson
  +String contactpersonnumber
  +String? feedback
  +List<Timestamp?> deadline
  +String pet
  +String toString()
}

class "pawfection::main.dart::MyApp" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "pawfection::main.dart::MyApp"

class "pawfection::splashscreen.dart::SplashScreen" {
  +_SplashScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pawfection::splashscreen.dart::SplashScreen"

class "pawfection::splashscreen.dart::_SplashScreenState" {
  +void initState()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "pawfection::splashscreen.dart::_SplashScreenState"

class "pawfection::service::task_service.dart::TaskService" {
  +Task taskFromJson()
  +Map<String, dynamic> taskToJson()
  +Task fromSnapshot()
  +List<Task> snapshotToTaskList()
  +List<Task> snapshotToTaskList_modified()
}

class "pawfection::service::pet_service.dart::PetService" {
  +Pet petFromJson()
  +Map<String, dynamic> petToJson()
  +Pet fromSnapshot()
  +List<Pet> snapshotToPetList()
  +List<Pet> snapshotToPetList_modified()
}

class "pawfection::service::user_service.dart::UserService" {
  +User userFromJson()
  +Map<String, dynamic> userToJson()
  +User fromSnapshot()
  +List<User> snapshotToUserList()
  +List<User> snapshotToUserList_modified()
}

class "pawfection::managerView.dart::ManagerView" {
  +int tab
  +State<ManagerView> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pawfection::managerView.dart::ManagerView"

class "pawfection::managerView.dart::_ManagerViewState" {
  -PageController _pageController
  +int maxCount
  +List<Widget> bottomBarPages
  +void dispose()
  +void initState()
  +Widget build()
}

"pawfection::managerView.dart::_ManagerViewState" o-- "flutter::src::widgets::page_view.dart::PageController"
"flutter::src::widgets::framework.dart::State" <|-- "pawfection::managerView.dart::_ManagerViewState"

class "pawfection::voluteerView.dart::VolunteerView" {
  +int tab
  +State<VolunteerView> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pawfection::voluteerView.dart::VolunteerView"

class "pawfection::voluteerView.dart::_VolunteerViewState" {
  -PageController _pageController
  +List<Widget> bottomBarPages
  +int maxCount
  +void dispose()
  +void initState()
  +Widget build()
}

"pawfection::voluteerView.dart::_VolunteerViewState" o-- "flutter::src::widgets::page_view.dart::PageController"
"flutter::src::widgets::framework.dart::State" <|-- "pawfection::voluteerView.dart::_VolunteerViewState"

class "pawfection::volunteerscreens::v_dashboard_screen.dart::VDashboardScreen" {
  +State<VDashboardScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pawfection::volunteerscreens::v_dashboard_screen.dart::VDashboardScreen"

class "pawfection::volunteerscreens::v_dashboard_screen.dart::_VDashboardScreenState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "pawfection::volunteerscreens::v_dashboard_screen.dart::_VDashboardScreenState"

class "pawfection::volunteerscreens::v_dashboard_screen.dart::TaskItem" {
  +Task task
  +Widget build()
}

"pawfection::volunteerscreens::v_dashboard_screen.dart::TaskItem" o-- "pawfection::models::task.dart::Task"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "pawfection::volunteerscreens::v_dashboard_screen.dart::TaskItem"

class "pawfection::volunteerscreens::v_dashboard_screen.dart::EmptyView" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "pawfection::volunteerscreens::v_dashboard_screen.dart::EmptyView"

class "pawfection::volunteerscreens::profile_picture_update_screen.dart::ProfilePictureUpdateScreen" {
  +String routetext
  +String petid
  +_ProfilePictureUpdateScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pawfection::volunteerscreens::profile_picture_update_screen.dart::ProfilePictureUpdateScreen"

class "pawfection::volunteerscreens::profile_picture_update_screen.dart::_ProfilePictureUpdateScreenState" {
  -bool _isLoading
  -bool _isSaved
  -ValueNotifier<File?> _croppedImageNotifier
  -TextEditingController _textEditingController
  +UserRepository userRepository
  +PetRepository petRepository
  +StorageRepository storageRepository
  -FirebaseAuth _auth
  +User currentUser
  -dynamic _cropImage()
  +dynamic pickImage()
  +void initState()
  +void dispose()
  +Widget build()
}

"pawfection::volunteerscreens::profile_picture_update_screen.dart::_ProfilePictureUpdateScreenState" o-- "flutter::src::foundation::change_notifier.dart::ValueNotifier<File>"
"pawfection::volunteerscreens::profile_picture_update_screen.dart::_ProfilePictureUpdateScreenState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"pawfection::volunteerscreens::profile_picture_update_screen.dart::_ProfilePictureUpdateScreenState" o-- "pawfection::repository::user_repository.dart::UserRepository"
"pawfection::volunteerscreens::profile_picture_update_screen.dart::_ProfilePictureUpdateScreenState" o-- "pawfection::repository::pet_repository.dart::PetRepository"
"pawfection::volunteerscreens::profile_picture_update_screen.dart::_ProfilePictureUpdateScreenState" o-- "pawfection::repository::storage_repository.dart::StorageRepository"
"pawfection::volunteerscreens::profile_picture_update_screen.dart::_ProfilePictureUpdateScreenState" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"pawfection::volunteerscreens::profile_picture_update_screen.dart::_ProfilePictureUpdateScreenState" o-- "firebase_auth::firebase_auth.dart::User"
"flutter::src::widgets::framework.dart::State" <|-- "pawfection::volunteerscreens::profile_picture_update_screen.dart::_ProfilePictureUpdateScreenState"

class "pawfection::volunteerscreens::profile_update_screen.dart::VProfileUpdateScreen" {
  +String imagePath
  +User user
  +State<VProfileUpdateScreen> createState()
}

"pawfection::volunteerscreens::profile_update_screen.dart::VProfileUpdateScreen" o-- "pawfection::models::user.dart::User"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pawfection::volunteerscreens::profile_update_screen.dart::VProfileUpdateScreen"

class "pawfection::volunteerscreens::profile_update_screen.dart::_VProfileUpdateScreenState" {
  -GlobalKey<FormState> _profileKey
  +GlobalKey<FormState> formKey
  +UserRepository userRepository
  +StorageRepository storageRepository
  -FirebaseAuth _auth
  -dynamic _form
  +dynamic alertmessage
  -List<dynamic> _experiences
  +List<dynamic> preferences
  -int _selectedFruit
  -void _showDialog()
  +void initState()
  +Widget build()
  -List<Widget> _buildForm()
  -List<Widget> _buildCupertinoForm()
}

"pawfection::volunteerscreens::profile_update_screen.dart::_VProfileUpdateScreenState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"pawfection::volunteerscreens::profile_update_screen.dart::_VProfileUpdateScreenState" o-- "pawfection::repository::user_repository.dart::UserRepository"
"pawfection::volunteerscreens::profile_update_screen.dart::_VProfileUpdateScreenState" o-- "pawfection::repository::storage_repository.dart::StorageRepository"
"pawfection::volunteerscreens::profile_update_screen.dart::_VProfileUpdateScreenState" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"flutter::src::widgets::framework.dart::State" <|-- "pawfection::volunteerscreens::profile_update_screen.dart::_VProfileUpdateScreenState"

class "pawfection::volunteerscreens::update_availability_screen.dart::UpdateAvailability" {
  +State<UpdateAvailability> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pawfection::volunteerscreens::update_availability_screen.dart::UpdateAvailability"

class "pawfection::volunteerscreens::update_availability_screen.dart::_UpdateAvailabilityState" {
  -GlobalKey<FormState> _dateKey
  -List<DateTime?> _date
  +Widget build()
}

"pawfection::volunteerscreens::update_availability_screen.dart::_UpdateAvailabilityState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"flutter::src::widgets::framework.dart::State" <|-- "pawfection::volunteerscreens::update_availability_screen.dart::_UpdateAvailabilityState"

class "pawfection::volunteerscreens::v_profile_screen.dart::VProfileScreen" {
  +State<VProfileScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pawfection::volunteerscreens::v_profile_screen.dart::VProfileScreen"

class "pawfection::volunteerscreens::v_profile_screen.dart::_VProfileScreenState" {
  +UserRepository userRepository
  -FirebaseAuth _auth
  +User currentUser
  +void initState()
  +Widget build()
  +Widget buildUpgradeButton1()
  +Widget buildProfile()
  +Widget buildUpgradeButton2()
  +Widget buildName()
  +Widget buildAbout()
  +Widget buildPreferences()
  +Widget buildExperiences()
}

"pawfection::volunteerscreens::v_profile_screen.dart::_VProfileScreenState" o-- "pawfection::repository::user_repository.dart::UserRepository"
"pawfection::volunteerscreens::v_profile_screen.dart::_VProfileScreenState" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"pawfection::volunteerscreens::v_profile_screen.dart::_VProfileScreenState" o-- "firebase_auth::firebase_auth.dart::User"
"flutter::src::widgets::framework.dart::State" <|-- "pawfection::volunteerscreens::v_profile_screen.dart::_VProfileScreenState"

class "pawfection::volunteerscreens::widgets::profile_widget.dart::ProfileWidget" {
  +Image image
  +bool isEdit
  +void Function() onClicked
  +Widget build()
  +Widget buildImage()
  +Widget buildEditIcon()
  +Widget buildCircle()
}

"pawfection::volunteerscreens::widgets::profile_widget.dart::ProfileWidget" o-- "flutter::src::widgets::image.dart::Image"
"pawfection::volunteerscreens::widgets::profile_widget.dart::ProfileWidget" o-- "dart::ui::void Function()"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "pawfection::volunteerscreens::widgets::profile_widget.dart::ProfileWidget"

class "pawfection::volunteerscreens::widgets::button_widget.dart::ButtonWidget" {
  +String text
  +void Function() onClicked
  +Widget build()
}

"pawfection::volunteerscreens::widgets::button_widget.dart::ButtonWidget" o-- "dart::ui::void Function()"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "pawfection::volunteerscreens::widgets::button_widget.dart::ButtonWidget"

class "pawfection::volunteerscreens::widgets::textfield_widget.dart::TextFieldWidget" {
  +int maxLines
  +String label
  +String text
  +void Function(String) onChanged
  +_TextFieldWidgetState createState()
}

"pawfection::volunteerscreens::widgets::textfield_widget.dart::TextFieldWidget" o-- "flutter::src::foundation::basic_types.dart::void Function(String)"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pawfection::volunteerscreens::widgets::textfield_widget.dart::TextFieldWidget"

class "pawfection::volunteerscreens::widgets::textfield_widget.dart::_TextFieldWidgetState" {
  +TextEditingController controller
  +void initState()
  +void dispose()
  +Widget build()
}

"pawfection::volunteerscreens::widgets::textfield_widget.dart::_TextFieldWidgetState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "pawfection::volunteerscreens::widgets::textfield_widget.dart::_TextFieldWidgetState"

class "pawfection::volunteerscreens::widgets::numbers_widget.dart::NumbersWidget" {
  +Widget build()
  +Widget buildDivider()
  +Widget buildButton()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "pawfection::volunteerscreens::widgets::numbers_widget.dart::NumbersWidget"


@enduml